name: Build Android APK
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 8 for App
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Build APK
        run: |
          # പുതിയ ഗ്രേഡിൽ Java 17 ആവശ്യപ്പെടുന്നതുകൊണ്ട് അത് ഇവിടെ സെറ്റ് ചെയ്യുന്നു
          export JAVA_HOME=$JAVA_HOME_17_X64
          cordova platform add android || true
          
          # ആപ്പ് ബിൽഡ് ചെയ്യാൻ Java 8 ലേക്ക് മാറുന്നു
          export JAVA_HOME=$JAVA_HOME_8_X64
          cordova build android --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: "platforms/android/app/build/outputs/apk/debug/*.apk"
